### ISSUE TITLE
python main.py --unity_test 1 error 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [EndingCredits/Neural-Episodic-Control#2]
Any idea what's wrong. I have installed all dependencies other than ALE....

```
python main.py --unity_test 1                                            ✔ master (origin/master)
Namespace(alpha=0.1, batch_size=32, delta=0.001, discount=0.99, display_step=5000, do_tests=0, env=None, env_type='Unity', epsilon=0.1, epsilon_anneal=5000000, epsilon_final=0.1, layer_sizes=[64], learn_step=4, learning_rate=1e-05, memory_size=500000, model=None, n_step=100, num_neighbours=50, replay_memory_size=100000, rom='roms/pong.bin', save_file=None, seed=123, test_count=5, test_step=50000, training_iters=5000000, unity_test=1)
2017-08-20 18:46:34.112860: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-20 18:46:34.112879: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-08-20 18:46:34.112884: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-20 18:46:34.112888: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "main.py", line 274, in <module>
    run_agent(args)
  File "main.py", line 46, in run_agent
    from unity_env import UnityEnvironment
  File "/Users/abhimanyuaryan/GitHub/Neural-Episodic-Control/unity_env.py", line 3, in <module>
    from unity_client.fetcher import Fetcher
  File "/Users/abhimanyuaryan/anaconda/lib/python3.6/site-packages/unity_client-0.0.1-py3.6.egg/unity_client/fetcher.py", line 3, in <module>
ModuleNotFoundError: No module named 'urllib2'
```

**Comment by EndingCredits** [comment]
Have you tried installing the urllib and urllib2 libraries? I can't rember exactly how you do this (I seem to recall some problems installing with pip), but it should be easy enough

I didn't include these as requirements as they're only required by the unit_client library.
